Backend MVP
RokoVarano/hotel_services_backend pull request #78
Opened 2021-11-27 17:34 UTC by notlfish

# What?
Pull request to add a Minimum Viable Product for the Hotel Services backend API, according to the [specifications](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md).

For this MVP the following tasks were done:
- [x] Specify and document the requests and responses handled by the API, see [the documentation](https://github.com/RokoVarano/hotel_services_backend#api-documentation)
- [x] Design a database for persisting the data, see [the ERD](https://github.com/RokoVarano/hotel_services_backend/blob/develop/docs/ERD.png).
- [x] Add configuration for allowing CORS and routing the requests.
- [x] Add models and migrations for database entities.
- [x] Add models validations.
- [x] Add controllers.
- [x] Add tests.
- [x] Add seeds to easily interact with the frontend during development.

### For more details on the implementation of each task, see the messages of the [closed Pull Requests](https://github.com/RokoVarano/hotel_services_backend/pulls?q=is%3Apr+is%3Aclosed) labeled as `MVP 1`.

2021-11-28 10:56 UTC, mcrd25 requested changes
Hi Team, 

As expected, good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!



## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._
- The majority (if not all since I see no deal breaker here) of work needs to be done on the Front-end

You can also consider:
-  I don't really have much else to say, but maybe be more consistent with tests. If you test name individually in negative scenario you should test it individually in positive scenario.
- Check how your organize your code in general

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-11-28 10:56 UTC, mcrd25 commented on Gemfile
> +
[OPTIONAL]
Swagger is good option for documentation, it'd make your API a bit more interactive. See [rswag gem](https://github.com/rswag/rswag)

2021-11-28 10:56 UTC, mcrd25 commented on README.md
>  Code: 200
Good job with this documentation! as mentioned above, you can go a step further usering swagger)

2021-12-01 12:22 UTC, mcrd25 commented
I believe I have reviewed this PR already. So I invalidated the review request since no changes were made. IT seems like you have some issues with creating services and recommendations, please double check this. If you need further assistance you are free to reach out to me personal and I'd be glad to trouble shoot with you

2021-12-01 14:05 UTC, notlfish commented
> I believe I have reviewed this PR already. So I invalidated the review request since no changes were made. IT seems like you have some issues with creating services and recommendations, please double check this. If you need further assistance you are free to reach out to me personal and I'd be glad to trouble shoot with you

2021-12-01 14:14 UTC, notlfish commented
## Note for the next reviewer:
The backend of this project had no changes since the first review, but there are lots of improvements on the frontend. Please, review them.

2021-12-01 14:42 UTC, MuriloRoque approved these changes
Hi @notlfish, @RokoVarano, @AdedayoOpeyemi, @afcastaneda223, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-12-02 22:09 UTC, merged